version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - echo Environment variables
      - env
      - echo Printing Docker Info 
      - docker info
      - echo Building sam...          
      - sam build
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET --s3-prefix $S3_PREFIX --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml 
