AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Swift Application

Parameters:
  UploadBucketName:
    Description: S3 Bucket to upload to 
    Type: String

Globals:
  Function:
    Timeout: 10
    CodeUri: . 
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512

Resources:
  SwiftSampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      BuildMethod: makefile
  UploadBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref UploadBucketName 
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref UploadBucket 
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: serverlessrepo.amazonaws.com
            Action: 
              - 's3:GetObject'
            Resource: 'arn:aws:s3:::swift-simple-lambda-bucket/*'
            Condition:
              StringEquals:
                'aws:SourceAccount': '767387487465'
Outputs:
  ApiEndpoint:
    Description: "API endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
