AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Swift Application

Globals:
  Function:
    Timeout: 10
    CodeUri: . 
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512

Resources:
  SwiftSampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      BuildMethod: makefile
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: swift-simple-lambda-bucket 
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket 
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: serverlessrepo.amazonaws.com
            Action: 
              - 's3:GetObject'
            Resource: 'arn:aws:s3:::swift-simple-lambda-bucket/*'
            Condition:
              StringEquals:
                'aws:SourceAccount': '767387487465'
#Metadata:
#  AWS::ServerlessRepo::Application:
#    Name: my-app
#    Description: hello world
#    Author: user1
#    SpdxLicenseId: Apache-2.0
#    LicenseUrl: LICENSE.txt
#    ReadmeUrl: README.md
#    Labels: ['tests']
#    HomePageUrl: https://github.com/user1/my-app-project
#    SemanticVersion: 0.0.1
#    SourceCodeUrl: https://github.com/user1/my-app-project

Outputs:
  ApiEndpoint:
    Description: "API endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
